# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<SCRIPT

echo Adding PUBLIC_IP to environment variables...
echo "export PUBLIC_IP=\`ifconfig eth1 | grep 'inet addr' | awk -F: '{print \$2}' | awk '{print \$1}'\`" >> /etc/profile

SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.network "public_network"

  config.vm.provision "docker"
  config.vm.provision "shell", inline: $script
end
