# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<SCRIPT

echo Running...

SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.provision "docker"

#  config.vm.provision "shell", inline: $script

  # Consul Web UI, :8500, http://localhost:8500/ui
  # Cluster / Raft Ports, :8300, :8301, :8302
  # All ports on which micro-services are running...
  for i in [8500, 8300, 8301, 8302]
    config.vm.network "forwarded_port", guest: i, host: i
  end
end
